### PR TITLE
Updates for 2.0

### PR DESCRIPTION
**Pull request by natefaubion**
Based off of the fundeps branch. Includes instances for MaybeT and ExceptT using Compose for the parallel applicative functor.

### CODE REVIEW

**Comment by paf31** [comment]
I think we decided that `Compose` had the wrong `Applicative` instance, didn't we? We need an `Applicative` for which `ap` and `<*>` are observationally equivalent, but where `<*>` is hopefully faster. But `Compose m (Either e)` and `ExceptT e m` will result in different effects from the base monad depending on the results of the first computations.

**Comment by natefaubion** [comment]
> I think we decided that Compose had the wrong Applicative instance, didn't we?

I don't think so? The problem was that the Applicative instance for ExceptT/MaybeT require the ap behavior, so by defining MonadPar using ExceptT/MaybeT on both sides, you don't get the correct parallelism. By switching to `Compose f Either/Maybe` on the parallel side, you get whatever parallelism f gives you. There is no ap requirement for Compose because it is not a Monad. @garyb?

**Comment by paf31** [comment]
Hmm, you're right, so there's no way to satisfy the spec above for `ExceptT` then

> We need an Applicative for which ap and <*> are observationally equivalent, but where <*> is hopefully faster.

That's disappointing because I'd like to be able to just replace `traverse` with `parTraverse` and get a speed up with no additional side-effects. Since the base monad might do anything (write to a database, the filesystem etc.), I think it's important to have a law like this, and we should just remove the instances if they're not law-abiding.

**Comment by natefaubion** [comment]
I don't think Aff will satisfy that spec, will it? It's `ap` behavior is sequential.

**Comment by paf31** [comment]
Hmm good point. Well maybe a law is too much to hope for then, and we should just optimize for parallelism and document possible issues clearly.

I'm just a little wary that an instance for a deep monad transformer stack might hide many possible issues like this.

**Comment by natefaubion** [comment]
I don't quite see what the problem is for the ExceptT/MaybeT instance though? If the point is to run things in parallel, you necessarily have to avoid the ap restriction. Isn't that the whole reason of having the transformation to some parallel applicative functor? If that law held, there would be know point in such a transformation and you'd just use the normal Applicative instance, wouldn't you? In the ExcepT/MaybeT cases, you get the same result, but because they are run in parallel you necessarily have to run both effects. Isn't this expected?

**Comment by natefaubion** [comment]
Another example is `MonadPar Validation Either`. I think this is a pretty sensible instance, and the whole point is that `parallel` avoids an ap restriction.

**Comment by paf31** [comment]
Yes I think you're right. The user has to be careful when using `parallel` anyway, depending on what their actions are doing. So I think this is fine, but we should still document it.

**Comment by paf31** [comment]
👍 to the `Validation` instance.

**Comment by garyb** [comment]
Is this formulation good to go then @paf31?

**Comment by garyb** [comment]
Also, I don't think I ever asked this before, but is the `MonadPar` formulation that much better? It seems less convenient in a bunch of ways, and I'm not sure what we gain from it.

**Comment by paf31** [comment]
👍  Yes looks good to me. Thanks @natefaubion

**Comment by paf31** [comment]
Which one seems less convenient?

**Comment by garyb** [comment]
I mean changing away from 

``` purescript
class Monad m <= MonadPar m where
  par :: forall a b c. (a -> b -> c) -> m a -> m b -> m c
```

**Comment by natefaubion** [comment]
One way it's less convenient is that you _must_ implement some other applicative functor for "parallel" effects. In the current formulation you can just use the provided `Parallel` type. Additionally you always have to add some `f` var in your type signatures even if you don't care about it.

I think this formulation has a lot of really cool properties (like Either/Validation), but I think I'd agree with the discussion I've read about it, that it seems more general than just concurrency. I think the current `MonadPar` has a simple, clear formulation (and only requires an `m`) for parallel processing.

**Comment by paf31** [comment]
What I don't like about the current formulation is that we're talking about an `Applicative` or `Alternative`, with all of the right laws, but we can't use any existing instance, and instead we have to write a duplicate `MonadPar` instance, and if we want an actual `Applicative`, we use `Parallel`, which is not the one we started with. On the other hand, this makes the corresponding parallel type constructor explicit as a type function.

**Comment by natefaubion** [comment]
I think that's fair. Maybe `MonadPar` is a bit of a misnomer? Are there any laws or relationships we can describe by requiring `(Monad m, Applicative f)`? Like I said, I think there are some really neat things you can talk about, but it seems way more general than for what we've used the existing `MonadPar`. I don't want to bikeshed too much though.

**Comment by paf31** [comment]
> Maybe MonadPar is a bit of a misnomer

Yes, perhaps we should rename it. Any thoughts? With named functional dependencies, we could call the dependency `Parallel`, but that's not a good name for the class IMO. Speaking of which, maybe `Parallel` there should be renamed to `ParallelCont` or something.

The connection with things like `V` and `ZipList` certainly is an interesting one. In Haskell, you could use parallel strategies or something, and _really_ evaluate those things in parallel, since `Applicative` means there should be no data dependencies getting in the way. Alas, in a strict language, I'm not sure there is a connection there, apart from conceptually.

**Comment by natefaubion** [comment]
I don't really have much of an opinion on the name, except that it should be a hilarious mashup of the two like `Paraquential` or `Sequarallel` 😆 

Does this formulation have any implications for libraries like purescript-coroutines?

**Comment by garyb** [comment]
`ApPar`? :wink:

This will resolve another minor annoyance I wanted to fix with the new release: if it is `MonadPar` then the module namespace should have been `Control.Monad.Parallel.Class` to match everywhere else we have a `MonadX` class (rather than `Control.Parallel.Class` - I get it wrong almost every time).

**Comment by paf31** [comment]
One possible downside of `ApPar` is that it might be confused with http://hackage.haskell.org/package/appar

**Comment by garyb** [comment]
Is it just coming up with a good name that is holding this up now? What was the problem with calling the class `Parallel`? (although we'd definitely need to rename the type to `ParallelCont` then to avoid collision).

**Comment by paf31** [comment]
Yes I think so :smile:. That suggestion sounds fine to me.

**Comment by paf31** [comment]
Or `ParCont` perhaps. `</bikeshed>`

**Comment by paf31** [comment]
> Does this formulation have any implications for libraries like purescript-coroutines?

Yes, I think it will, but I'm pretty sure it will be fine. I'll start working on updating my libraries shortly after core (and some of contrib) is finished.

**Comment by natefaubion** [comment]
I personally like ParAp, as it's fairly descriptive.

**Comment by paf31** [comment]
It's difficult to come up with a name which suggests a bidirectional type function between `Monad`s and `Applicative`s, but prefers neither... ☹️

**Comment by paf31** [comment]
If we had infix type constructors we could say something like ``f `Parallelizes` m``.

**Comment by paf31** [comment]
I'll merge this into the `fundeps` branch anyway, and we can decide on names over there.

**Pull request merged**
