### PR TITLE
Implements V Either Parallel, fixes #26

### LINKED ISSUE #26: Instance Parallel (V err) (Either err)
Might be nice to have, and I think it makes sense. We already depend on either here, so we'd only need to add a dependency on validation, I think.

### PR DESCRIPTION
**Pull request by reactormonk**
I think I got it the right way round.

### CODE REVIEW

**Comment by garyb** [comment]
I don't think we want this instance, based on previous discussions, since it globally restricts `V` to be the only `Parallel` for `Either`: https://github.com/purescript/purescript-validation/pull/9, #21

**Comment by reactormonk** [comment]
Ah, duh.

**Comment by hdgarrood** [comment]
Oops, sorry, I hadn't seen those. Are there any other candidates for either `Either` or `V` for an alternative `Parallel` instance, though? If not, is globally restricting the instance in this way such a bad thing?

**Comment by hdgarrood** [comment]
Oh of course, thanks.

**Comment by hdgarrood** [comment]
I would like to suggest reconsidering this, in light of https://github.com/purescript/purescript-validation/issues/27. Whether or not we deprecate the Semiring version of Validation, I feel like the Semigroup version likely enjoys a lot more use and makes more sense as the default instance to be paired with Either.

**Pull request closed without merging**
